<a href="https://colab.research.google.com/github/Balaji-CSE/2127200501029/blob/main/Cleveland.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, KFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from mlxtend.classifier import StackingCVClassifier
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix
import statistics

df = pd.read_csv("cleveland_ds.csv")


In [2]:
#DATA CLEANING Filling missing vales with mode values

import statistics
needs_to_clean = ['ca', 'thal']
for i in needs_to_clean:
    X = df[i].values
    data = np.array(X)
    mode_result = statistics.mode(data)
    df[i] = df[i].replace('?', mode_result)
    print("Mode:", mode_result)

vandhu = ['target']

#Standardizing target variable...
df.loc[df['target'] > 0, 'target'] = 1

Mode: 0.0
Mode: 3.0


In [3]:
#splitting into features and class label

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X = df.drop('target',axis = 1)
y = df['target']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 23)
scaler  = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



KNN Classifier



In [21]:
#KNN

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
knn = KNeighborsClassifier(n_neighbors=11)
knn.fit(X_train,y_train)
knnpred = knn.predict(X_test)
accuracy = round(accuracy_score(y_test, knnpred)*100,2)
print("Accuracy = ",accuracy)

Accuracy =  85.25


In [12]:
#EMPTY

In [ ]:
cvscore = cross_val_score(KNeighborsClassifier(n_neighbors=11),X,y,cv = 10)
cvscore

array([0.67741935, 0.61290323, 0.58064516, 0.73333333, 0.8       ,
       0.53333333, 0.6       , 0.83333333, 0.6       , 0.7       ])

K-Fold Cross Validation (10fold)

In [ ]:

k = 10  # Number of folds
kf = KFold(n_splits=k, shuffle=True, random_state=23)

total_accuracy = 0

for train_index, test_index in kf.split(X):
    X_train_fold, X_test_fold = X.iloc[train_index], X.iloc[test_index]
    y_train_fold, y_test_fold = y.iloc[train_index], y.iloc[test_index]

    classifier = KNeighborsClassifier(n_neighbors=11)
    classifier.fit(X_train_fold, y_train_fold)
    y_pred_fold = classifier.predict(X_test_fold)


    cm = confusion_matrix(y_test_fold, y_pred_fold)
    fold_accuracy = accuracy_score(y_test_fold, y_pred_fold) * 100
    print('Accuracy for this fold:', fold_accuracy)
    total_accuracy += fold_accuracy
    print("Confusion Matrix for Fold:")
    print(cm)

mean_accuracy = total_accuracy / k
print("Mean Accuracy =", mean_accuracy)

Accuracy for this fold: 64.51612903225806
Confusion Matrix for Fold:
[[12  4]
 [ 7  8]]
Accuracy for this fold: 67.74193548387096
Confusion Matrix for Fold:
[[14  4]
 [ 6  7]]
Accuracy for this fold: 64.51612903225806
Confusion Matrix for Fold:
[[10  7]
 [ 4 10]]
Accuracy for this fold: 63.33333333333333
Confusion Matrix for Fold:
[[12  5]
 [ 6  7]]
Accuracy for this fold: 73.33333333333333
Confusion Matrix for Fold:
[[13  1]
 [ 7  9]]
Accuracy for this fold: 63.33333333333333
Confusion Matrix for Fold:
[[12  7]
 [ 4  7]]
Accuracy for this fold: 63.33333333333333
Confusion Matrix for Fold:
[[11  6]
 [ 5  8]]
Accuracy for this fold: 63.33333333333333
Confusion Matrix for Fold:
[[12  3]
 [ 8  7]]
Accuracy for this fold: 63.33333333333333
Confusion Matrix for Fold:
[[13  6]
 [ 5  6]]
Accuracy for this fold: 53.333333333333336
Confusion Matrix for Fold:
[[ 6  6]
 [ 8 10]]
Mean Accuracy = 64.01075268817205


SVM Classifier


In [16]:
#SVM

Svm = SVC(kernel = 'linear',C=2,probability=True)
Svm.fit(X_train,y_train)
Svmpred = Svm.predict(X_test)
cm = confusion_matrix(y_test,Svmpred)
print(cm)
accuracy = round(accuracy_score(y_test, Svmpred)*100,2)
print("Accuracy = ",accuracy)


[[26  7]
 [ 6 22]]
Accuracy =  78.69


Decision Tree


In [15]:
#DT

dt = DecisionTreeClassifier(criterion='entropy',random_state = 23,max_depth=4)
dt.fit(X_train,y_train)
dtpred = dt.predict(X_test)
accuracy = round(accuracy_score(y_test, dtpred)*100,2)
print("Accuracy = ",accuracy)

Accuracy =  78.69


In [ ]:

k = 10  # Number of folds
kf = KFold(n_splits=k, shuffle=True, random_state=23)

total_accuracy = 0

for train_index, test_index in kf.split(X):
    X_train_fold, X_test_fold = X.iloc[train_index], X.iloc[test_index]
    y_train_fold, y_test_fold = y.iloc[train_index], y.iloc[test_index]

    classifier =DecisionTreeClassifier(criterion='entropy',random_state = 23,max_depth=4)
    classifier.fit(X_train_fold, y_train_fold)
    y_pred_fold = classifier.predict(X_test_fold)


    cm = confusion_matrix(y_test_fold, y_pred_fold)
    fold_accuracy = accuracy_score(y_test_fold, y_pred_fold) * 100
    print('Accuracy for this fold:', fold_accuracy)
    total_accuracy += fold_accuracy
    print("Confusion Matrix for Fold:")
    print(cm)

mean_accuracy = total_accuracy / k
print("Mean Accuracy =", mean_accuracy)

Accuracy for this fold: 77.41935483870968
Confusion Matrix for Fold:
[[14  2]
 [ 5 10]]
Accuracy for this fold: 80.64516129032258
Confusion Matrix for Fold:
[[16  2]
 [ 4  9]]
Accuracy for this fold: 70.96774193548387
Confusion Matrix for Fold:
[[12  5]
 [ 4 10]]
Accuracy for this fold: 83.33333333333334
Confusion Matrix for Fold:
[[15  2]
 [ 3 10]]
Accuracy for this fold: 70.0
Confusion Matrix for Fold:
[[10  4]
 [ 5 11]]
Accuracy for this fold: 86.66666666666667
Confusion Matrix for Fold:
[[18  1]
 [ 3  8]]
Accuracy for this fold: 70.0
Confusion Matrix for Fold:
[[12  5]
 [ 4  9]]
Accuracy for this fold: 76.66666666666667
Confusion Matrix for Fold:
[[12  3]
 [ 4 11]]
Accuracy for this fold: 80.0
Confusion Matrix for Fold:
[[16  3]
 [ 3  8]]
Accuracy for this fold: 73.33333333333333
Confusion Matrix for Fold:
[[11  1]
 [ 7 11]]
Mean Accuracy = 76.90322580645162


In [14]:
#GaussianNB
nb = GaussianNB()
nb.fit(X_train,y_train)
nbpred = nb.predict(X_test)
print("Accuracy of NB = " , accuracy_score(y_test,nbpred)*100)

Accuracy of NB =  81.9672131147541


In [8]:
pip install tensorflow-addons

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 612.1/612.1 kB 7.5 MB/s eta 0:00:00


In [13]:
#Deep Learning Model

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
import tensorflow_addons as tfa
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model


input_layer = Input(shape=(X_train.shape[1],))
d1 = Dense(units=100, activation='relu')(input_layer)
d2 = Dense(units=100, activation='relu')(d1)
d3 = Dense(units=100, activation='relu')(d2)
d4 = Dense(units=100, activation='relu')(d3)
d5 = Dense(units=100, activation='relu')(d4)
d6 = Dense(units=100, activation='relu')(d5)
d7 = Dense(units=100, activation='relu')(d6)
d8 = Dense(units=100, activation='relu')(d7)
# d9 = Dense(units=100, activation='relu')(d8)
output_layer = Dense(units=1, activation='sigmoid')(d8)

model = Model(inputs=input_layer, outputs=output_layer)

# Compile the model with metrics and optimizer
model.compile(
    loss='binary_crossentropy',
    metrics=['accuracy', tf.keras.metrics.Recall(name="Sensitivity"),
             tf.keras.metrics.SpecificityAtSensitivity(0.5, name="Specificity"),
             tfa.metrics.F1Score(num_classes=1, threshold=0.5)],
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001)
)

# Train the model
model.fit(x=X_train, y=y_train, batch_size=2, epochs=120)

# Evaluate the model on the test data
test_loss, test_accuracy, sensitivity, specificity, f1_score = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_accuracy * 100:.2f}%")
print(f"Sensitivity (Recall): {sensitivity:.2f}")
print(f"Specificity: {specificity:.2f}")
print("x=" + str(list(map('{:.2f}%'.format,f1_score))))



Epoch 1/120
121/121 [==============================] - 6s 7ms/step - loss: 0.5142 - accuracy: 0.7479 - Sensitivity: 0.6937 - Specificity: 0.9313 - f1_score: 0.7163
Epoch 2/120
121/121 [==============================] - 1s 5ms/step - loss: 0.3524 - accuracy: 0.8554 - Sensitivity: 0.8018 - Specificity: 0.9771 - f1_score: 0.8357
Epoch 3/120
121/121 [==============================] - 1s 5ms/step - loss: 0.2975 - accuracy: 0.8719 - Sensitivity: 0.8378 - Specificity: 1.0000 - f1_score: 0.8571
Epoch 4/120
121/121 [==============================] - 1s 8ms/step - loss: 0.2666 - accuracy: 0.8967 - Sensitivity: 0.8649 - Specificity: 0.9924 - f1_score: 0.8848
Epoch 5/120
121/121 [==============================] - 1s 7ms/step - loss: 0.2579 - accuracy: 0.8884 - Sensitivity: 0.8468 - Specificity: 1.0000 - f1_score: 0.8744
Epoch 6/120
121/121 [==============================] - 1s 5ms/step - loss: 0.2266 - accuracy: 0.9091 - Sensitivity: 0.8559 - Specificity: 1.0000 - f1_score: 0.8962
Epoch 7/120
121/

In [ ]:
#Bagging Classifier

In [19]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
base_classifier = DecisionTreeClassifier(random_state=42)
bagging_classifier = BaggingClassifier(base_classifier, n_estimators=10, random_state=42)
bagging_classifier.fit(X_train, y_train)
y_pred = bagging_classifier.predict(X_test)
accuracy = round(accuracy_score(y_test, y_pred)*100,2)
print("Accuracy: ",accuracy)

Accuracy:  78.69


AdaBoost Classifier


In [18]:
from sklearn.ensemble import AdaBoostClassifier
base_classifier = DecisionTreeClassifier(max_depth=6)
adaboost_classifier = AdaBoostClassifier(base_classifier, n_estimators=50, random_state=42)
adaboost_classifier.fit(X_train, y_train)
y_pred = adaboost_classifier.predict(X_test)
accuracy = round(accuracy_score(y_test, y_pred)*100,2)
print("Accuracy:", accuracy)

Accuracy: 85.25


QDA

In [17]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
qda = QuadraticDiscriminantAnalysis()
qda.fit(X_train, y_train)
y_pred = qda.predict(X_test)
accuracy = round(accuracy_score(y_test, y_pred)*100,2)
print("Accuracy:", accuracy)


Accuracy: 80.33


Ensembling Techniques

In [22]:
#ENSEMBLING TECHNIQUES

estimator = []
estimator.append(('SVM', Svm))
estimator.append(('DT', dt))
estimator.append(('KNN', knn))
estimator.append(('QDA', qda))
#estimator.append(('NB', nb))
estimator.append(('bagging',bagging_classifier))
#estimator.append(('boosting',adaboost_classifier))

from sklearn.ensemble import VotingClassifier
Soft = VotingClassifier(estimators = estimator, voting ='soft')
Soft.fit(X_train, y_train)
y_pred = Soft.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
print(cm)
score = accuracy_score(y_test, y_pred)
print("Accuracy After Ensembling = " , score*100)

[[29  4]
 [ 5 23]]
Accuracy After Ensembling =  85.24590163934425


In [ ]:
pip install keras numpy scikit-learn
